apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uphl8btqi-python
  janus-idp.io/tekton: uphl8btqi-python
  backstage.io/kubernetes-id: uphl8btqi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uphl8btqi-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
